# Use an official Node.js runtime as the base image
FROM node:14

# Set the working directory in the container
WORKDIR C:\Users\AVuser\Desktop\A1\Container1\app.js

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install the application dependencies
RUN npm install

# Copy the application code to the container
COPY . .

# Expose the port the application listens on
EXPOSE 5000

# Set the command to run the application
CMD ["node", "app.js"]
