apiVersion: apps/v1
kind: Deployment
metadata:
  name: container2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container2
  template:
    metadata:
      labels:
        app: container2
    spec:
      containers:
        - name: container2
          image: us-central1-docker.pkg.dev/csci5409-390211/container2/container2-image:1.0
          imagePullPolicy: Always
          volumeMounts:
            - name: data-volume
              mountPath: /app/filedata
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: my-pvc
